
# network architecture
model-module: "espnet.nets.chainer_backend.boundary:Boundary"
layer-type: res

# minibatch related
batch-size: 50
maxlen-in: 512  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adam
epochs: 30
patience: 0
grad-clip: 10

dropout-rate: 0.5
bound-res-kernel: 5