
# network architecture
model-module: "espnet.nets.chainer_backend.boundary:Boundary"
layer-type: rnn

# minibatch related
batch-size: 100
maxlen-in: 512  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adam
epochs: 15
patience: 3
grad-clip: 10

dropout-rate: 0.5
