
# network architecture
model-module: "espnet.nets.chainer_backend.e2e_asr_unsup_1:E2E"

# minibatch related
batch-size: 32
maxlen-in: 512  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: noam
epochs: 300
grad-clip: 5
mtlalpha: 1.0

# model related
dropout-rate: 0.3


# RNNLM
phnlm-config: "exp/train_lm_chainer_lm_phon_unpaired/model.json"
phnlm-model: "exp/train_lm_chainer_lm_phon_unpaired/rnnlm.model.best"

phn-file: "data/lang_phone/phone_units.txt"
