# network architecture
# encoder related

elayers: 4
eunits: 1024


# decoder related
dlayers: 1
dunits: 1024
# attention related

adim: 1024


# hybrid CTC/attention
mtlalpha: 1.0

# minibatch related
batch-size: 35
maxlen-in: 600  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adam
epochs: 14
patience: 0

# scheduled sampling option
model-module: "espnet.nets.chainer_backend.unsupervised_cnn:AcousticModel"


# RNNLM
rnnlm-config: "exp/train_rnnlm_chainer_lm/model.json"
rnnlm-model: "exp/train_rnnlm_chainer_lm/rnnlm.model.best"
